
import Navbar from "./components/UI/navbar";
import "./globals.css";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>



     
        <Navbar></Navbar>
        <div className="container mx-auto px-4 sm:px-6 lg:px-8">
        {children}
        </div>
        
        </body>
    </html>
  );
}
